Generate a valid imagelabel even for type 'none'
This backports upstream fix to Frobisher

Commit 2ce63c1 added imagelabel generation when relabeling is turned
off. But we weren't filling out the sensitivity for type 'none' labels,
resulting in an invalid label:

$ virsh managedsave domain
error: unable to set security context 'system_u:object_r:svirt_image_t'
on fd 28: Invalid argument

This fixes the following bug
https://bugzilla.linux.ibm.com/show_bug.cgi?id=99332

Signed-off-by: Pradipta Kr. Banerjee <bpradip@in.ibm.com>